### ISSUE TITLE
Wylleman Ruben - LOG-T5

### ISSUE THREAD

**Issue by rubenwylleman** [kristobo/tuinen-angular#1]
user: gg / pasw: hij ==>bij invoer van deze verkeerde user en pasw groene achtergrond van de login button wordt extra groot. Bij activatie keyboard terug normaal.

![getimage](https://cloud.githubusercontent.com/assets/25935742/26119184/b0e4f2ba-3a6c-11e7-8377-e2e8552922ad.png)

**Comment by kristobo** [comment]
gefixed
