### ISSUE TITLE
Wylleman Ruben - MAT-T3

### ISSUE THREAD

**Issue by rubenwylleman** [kristobo/tuinen-angular#7]
Na het invullen van wat materiaal keer je terug naar je opdracht, als je meerder materialen hebt ingevoerd en je bent terug op de opdracht. Als je van hier nu terug keert met 'back' toets op de telefoon keer je ook terug in alle schermen die je geopend hebt voor materiaal in te vullen.

![getimage 1](https://cloud.githubusercontent.com/assets/25935742/26120343/a6d9e01a-3a70-11e7-9426-7f7b788de71f.png)
![getimage 2](https://cloud.githubusercontent.com/assets/25935742/26120347/ab105754-3a70-11e7-8a8e-2cb0f8c0dc9d.png)

**Comment by kristobo** [comment]
Is standaard android behavior, is ook bij apps zoals 2dehands, immoweb,..
